import type { AnimationConfig, SubtitleStyle } from "../types/subtitle.ts";
import { DEFAULT_ANIMATION, DEFAULT_SUBTITLE_STYLE } from "../types/subtitle.ts";

/**
 * Built-in caption style library, organised into STYLE FAMILIES (P20.2).
 *
 * A family is a recognisable visual system, not a colour scheme: each one fixes a typographic
 * personality, a layout/position, a container treatment, an emphasis strategy and a motion
 * language, and every preset in it expresses that system. Families supersede the P5-era
 * `category` grouping (Creator/Dynamic/Highlight/Clean/…), which grouped by *use* and ended up with
 * 25 of 45 presets being "white caps + black outline + fade" at the same position.
 *
 * `family` is plain data on each preset — the renderers (preview + ASS export) never look at it or
 * at a preset id; they only ever consume the resolved SubtitleStyle/AnimationConfig. See
 * __tests__/style-family-audit.test.ts for the contract each family must keep and the pairwise
 * differentiation guard, and docs/STYLE-FAMILIES.md for the design of each family.
 *
 * Migration safety: no preset id was removed. A preset folded into another ("merged") stays in the
 * array, byte-identical, flagged `replacedBy` — it still resolves through getPreset() (templates,
 * recommendations, legacy references) but is hidden from the picker.
 */
export const STYLE_FAMILIES = [
  "minimal",
  "bold-creator",
  "karaoke",
  "editorial",
  "cinematic",
  "neon",
  "sticker",
  "comic",
  "podcast",
  "documentary",
  "meme",
  "handwritten",
] as const;
export type StyleFamily = (typeof STYLE_FAMILIES)[number];

export const FAMILY_INFO: Record<StyleFamily, { label: string; tagline: string }> = {
  minimal: { label: "Minimal", tagline: "Quiet, small type with lots of negative space" },
  "bold-creator": { label: "Bold Creator", tagline: "Huge heavy caps that punch in with the active word" },
  karaoke: { label: "Karaoke", tagline: "Readable base text, a strong sweep on the spoken word" },
  editorial: { label: "Editorial", tagline: "Serif type placed deliberately, like a magazine caption" },
  cinematic: { label: "Cinematic", tagline: "Wide-tracked film subtitles, low in the frame" },
  neon: { label: "Neon", tagline: "Luminous, high-contrast type with a glowing edge" },
  sticker: { label: "Sticker", tagline: "Solid rounded chips behind playful type" },
  comic: { label: "Comic", tagline: "Lettering with thick outlines and a springy bounce" },
  podcast: { label: "Podcast", tagline: "Highly readable left-aligned lower thirds" },
  documentary: { label: "Documentary", tagline: "Informational bars with calm, conservative motion" },
  meme: { label: "Meme", tagline: "Enormous impact lettering at the frame edges" },
  handwritten: { label: "Handwritten", tagline: "Pen and marker lettering in an organic layout" },
};

export interface SubtitlePresetDef {
  id: string;
  name: string;
  description: string;
  family: StyleFamily;
  /** One of the two flagship styles that define the family's look (see the family-audit test). */
  representative?: boolean;
  /** Set on a preset that was folded into another: it stays resolvable by id but is hidden from the picker. */
  replacedBy?: string;
  style: SubtitleStyle;
  animation: AnimationConfig;
}

function s(overrides: Partial<SubtitleStyle>): SubtitleStyle {
  return { ...DEFAULT_SUBTITLE_STYLE, ...overrides };
}
function a(overrides: Partial<AnimationConfig>): AnimationConfig {
  return { ...DEFAULT_ANIMATION, ...overrides };
}

export const BUILT_IN_PRESETS: SubtitlePresetDef[] = [
  // ───────────────────────── Minimal ─────────────────────────
  {
    id: "minimal",
    name: "Minimal",
    description: "Small sentence-case text, no outline, a whisper of shadow — lets the video breathe.",
    family: "minimal",
    representative: true,
    style: s({
      fontFamily: "DM Sans",
      fontWeight: 500,
      fontSize: 46,
      textCase: "sentence",
      outlineEnabled: false,
      shadowEnabled: true,
      shadowBlur: 20,
      shadowOffsetY: 2,
      shadowOpacity: 0.7,
      y: 84, // a little above the bottom edge: clear of platform UI, and distinct from Cinematic's y: 88
      wordHighlight: false,
    }),
    animation: a({ entrance: "fade", exit: "none", word: "none", durationSec: 0.3 }),
  },
  {
    id: "minimal-left",
    name: "Minimal Left",
    description: "Tiny lowercase text tucked into the bottom-left corner, sliding up gently.",
    family: "minimal",
    representative: true,
    style: s({
      fontFamily: "Manrope",
      fontWeight: 500,
      fontSize: 42,
      textCase: "lowercase",
      letterSpacing: 1.5,
      color: "#F3F4F6",
      opacity: 0.92,
      outlineEnabled: false,
      shadowBlur: 18,
      shadowOffsetY: 2,
      shadowOpacity: 0.7,
      x: 6,
      y: 93,
      align: "left",
      boxWidthPercent: 62,
      wordHighlight: true,
      highlightColor: "#FDE68A",
    }),
    animation: a({ entrance: "slide-up", exit: "fade", word: "color", durationSec: 0.35 }),
  },
  {
    // Survivor of the Classic / Clean / Clean White merge (the latter two stay resolvable, hidden).
    id: "classic",
    name: "Classic",
    description: "Timeless white text with a soft outline.",
    family: "minimal",
    style: s({ fontFamily: "Inter", fontWeight: 700, fontSize: 58, textCase: "sentence", outlineWidth: 5, wordHighlight: false }),
    animation: a({ entrance: "fade", word: "none" }),
  },
  {
    // Survivor of the Mono / Wide Type merge.
    id: "mono",
    name: "Mono",
    description: "Wide, even letter-spacing for a technical, monospace-inspired feel.",
    family: "minimal",
    style: s({ fontFamily: "Roboto", fontWeight: 500, fontSize: 48, textCase: "none", letterSpacing: 3, outlineWidth: 2, wordHighlight: false }),
    animation: a({ entrance: "fade", word: "none" }),
  },
  {
    id: "modern",
    name: "Modern",
    description: "Geometric sans, no outline, a soft violet underline on the spoken word.",
    family: "minimal",
    style: s({
      fontFamily: "Urbanist",
      fontWeight: 700,
      fontSize: 48,
      textCase: "none",
      outlineEnabled: false,
      shadowEnabled: true,
      shadowBlur: 12,
      y: 86,
      wordHighlight: true,
      highlightColor: "#A78BFA",
    }),
    animation: a({ entrance: "fade", word: "underline", durationSec: 0.25 }),
  },

  // ───────────────────────── Bold Creator ─────────────────────────
  {
    // Survivor of the Bold / Power Words / Creator Bold merge.
    id: "bold",
    name: "Bold",
    description: "Huge, heavy caps dead-centre in the frame, popping in with a yellow word hit.",
    family: "bold-creator",
    representative: true,
    style: s({
      fontFamily: "Archivo",
      fontWeight: 900,
      fontSize: 80,
      outlineWidth: 9,
      y: 50,
      vAlign: "center",
      boxWidthPercent: 84,
      wordHighlight: true,
      highlightColor: "#FACC15",
      activeWordScale: 1.15,
    }),
    animation: a({ entrance: "pop", word: "scale", durationSec: 0.2 }),
  },
  {
    id: "mrbeast",
    name: "MrBeast-style",
    description: "Huge yellow bouncy caps with a thick black outline.",
    family: "bold-creator",
    representative: true,
    style: s({
      fontFamily: "Anton",
      fontWeight: 400,
      fontSize: 84,
      textCase: "uppercase",
      color: "#FFFFFF",
      highlightColor: "#FFD400",
      outlineWidth: 10,
      activeWordScale: 1.25,
      wordHighlight: true,
    }),
    animation: a({ entrance: "bounce", word: "bounce", durationSec: 0.25 }),
  },
  {
    id: "tiktok",
    name: "TikTok",
    description: "The viral look: bold caps, cyan highlight pop.",
    family: "bold-creator",
    style: s({ fontFamily: "Poppins", fontWeight: 800, fontSize: 76, textCase: "uppercase", y: 58, highlightColor: "#22D3EE", activeWordScale: 1.18 }),
    animation: a({ entrance: "pop", word: "scale", durationSec: 0.15 }),
  },
  {
    id: "punch",
    name: "Punch",
    description: "Drops in from above, high in the frame, every word landing with a hard scale-and-colour hit.",
    family: "bold-creator",
    style: s({
      fontFamily: "Archivo Black",
      fontWeight: 400,
      fontSize: 76,
      textCase: "uppercase",
      outlineWidth: 10,
      y: 30,
      vAlign: "center",
      wordHighlight: true,
      highlightColor: "#FF6B35",
      activeWordScale: 1.2,
    }),
    animation: a({ entrance: "slide-down", word: "scale", durationSec: 0.18 }),
  },
  {
    id: "gaming",
    name: "Gaming",
    description: "Neon highlight with aggressive scale-pop.",
    family: "bold-creator",
    style: s({
      fontFamily: "Archivo",
      fontWeight: 900,
      fontSize: 70,
      textCase: "uppercase",
      color: "#E5E7EB",
      highlightColor: "#A3E635",
      outlineColor: "#111827",
      outlineWidth: 7,
      activeWordScale: 1.3,
      x: 6,
      y: 8,
      align: "left",
      vAlign: "top",
      boxWidthPercent: 58,
    }),
    animation: a({ entrance: "slide-right", exit: "slide-left", word: "scale", durationSec: 0.15 }),
  },
  {
    id: "jump-pop",
    name: "Jump Pop",
    description: "Mixed-case Poppins; the caption springs in and each word bounces as it's spoken.",
    family: "bold-creator",
    style: s({
      fontFamily: "Poppins",
      fontWeight: 800,
      fontSize: 72,
      textCase: "none",
      outlineWidth: 6,
      y: 74,
      wordHighlight: true,
      highlightColor: "#A3E635",
      activeWordScale: 1.25,
    }),
    animation: a({ entrance: "bounce", word: "bounce", durationSec: 0.25 }),
  },
  // Folded into "Bold" — kept byte-identical so existing references resolve, hidden from the picker.
  {
    id: "power-words",
    name: "Power Words",
    description: "Emphasized words jump bigger, bolder, and into an accent color.",
    family: "bold-creator",
    replacedBy: "bold",
    style: s({
      fontFamily: "Archivo",
      fontWeight: 900,
      fontSize: 72,
      textCase: "uppercase",
      outlineWidth: 7,
      wordHighlight: true,
      highlightColor: "#FF3366",
      activeWordScale: 1.3,
    }),
    animation: a({ entrance: "pop", word: "scale", durationSec: 0.18 }),
  },
  {
    id: "creator-bold",
    name: "Creator Bold",
    description: "A confident, condensed creator base look — the loudest possible plain caption.",
    family: "bold-creator",
    replacedBy: "bold",
    style: s({ fontFamily: "League Spartan", fontWeight: 900, fontSize: 74, textCase: "uppercase", outlineWidth: 9, wordHighlight: false }),
    animation: a({ entrance: "pop", word: "none", durationSec: 0.2 }),
  },

  // ───────────────────────── Karaoke ─────────────────────────
  {
    id: "karaoke",
    name: "Karaoke",
    description: "Word-by-word color sweep, sing-along style.",
    family: "karaoke",
    representative: true,
    style: s({
      fontFamily: "Montserrat",
      fontWeight: 800,
      fontSize: 66,
      wordHighlight: true,
      highlightColor: "#22D3EE",
      color: "#E5E7EB",
      activeWordScale: 1.15,
      y: 80,
    }),
    animation: a({ entrance: "none", exit: "none", word: "scale", durationSec: 0.15 }),
  },
  {
    id: "word-focus",
    name: "Word Focus",
    description: "Base text sits dim and quiet; the active word turns bright white and pulls focus.",
    family: "karaoke",
    representative: true,
    style: s({ fontFamily: "Inter", fontWeight: 600, fontSize: 56, outlineWidth: 3, color: "#9CA3AF", wordHighlight: true, highlightColor: "#FFFFFF" }),
    animation: a({ entrance: "fade", word: "color" }),
  },
  {
    // Survivor of the Highlight / Active Highlight merge.
    id: "highlight",
    name: "Highlight",
    description: "Background box sweeps behind the active word.",
    family: "karaoke",
    // highlightColor was #000000 until Task 87426's P6 audit: a black active-word background chip is
    // invisible against SUBLY's default black composition background; #FB923C reads on both.
    style: s({ fontFamily: "Poppins", fontWeight: 700, fontSize: 60, wordHighlight: true, highlightColor: "#FB923C", color: "#FFFFFF" }),
    animation: a({ entrance: "fade", word: "bg-highlight" }),
  },
  {
    id: "marker",
    name: "Marker",
    description: "Mixed-case type; a highlighter-yellow box swipes behind the active word as the caption slides up.",
    family: "karaoke",
    style: s({ fontFamily: "DM Sans", fontWeight: 700, fontSize: 56, textCase: "none", y: 80, wordHighlight: true, highlightColor: "#FFE066" }),
    animation: a({ entrance: "slide-up", word: "bg-highlight" }),
  },
  {
    id: "color-sweep",
    name: "Color Sweep",
    description: "Soft, light-weight mixed-case text; a teal underline travels with the spoken word.",
    family: "karaoke",
    style: s({
      fontFamily: "Montserrat",
      fontWeight: 600,
      fontSize: 54,
      textCase: "none",
      color: "#D1D5DB",
      outlineWidth: 3,
      shadowEnabled: false,
      y: 76,
      wordHighlight: true,
      highlightColor: "#2DD4BF",
    }),
    animation: a({ entrance: "fade", word: "underline", durationSec: 0.12 }),
  },
  {
    id: "pulse-highlight",
    name: "Pulse Highlight",
    description: "Sits high in the frame, drops in, and the spoken word bounces larger in pink.",
    family: "karaoke",
    style: s({
      fontFamily: "Urbanist",
      fontWeight: 800,
      fontSize: 56,
      textCase: "none",
      y: 12,
      vAlign: "top",
      boxWidthPercent: 78,
      wordHighlight: true,
      highlightColor: "#F472B6",
      activeWordScale: 1.25,
    }),
    animation: a({ entrance: "slide-down", word: "bounce", durationSec: 0.2 }),
  },
  // Folded into "Highlight".
  {
    id: "active-highlight",
    name: "Active Highlight",
    description: "The current word gets a bold, contrasting background chip.",
    family: "karaoke",
    replacedBy: "highlight",
    style: s({ fontFamily: "Poppins", fontWeight: 700, fontSize: 58, wordHighlight: true, highlightColor: "#7C3AED" }),
    animation: a({ entrance: "fade", word: "bg-highlight" }),
  },

  // ───────────────────────── Editorial ─────────────────────────
  {
    id: "editorial",
    name: "Editorial",
    description: "Warm serif, sentence case, set flush-left in the lower third like a magazine caption.",
    family: "editorial",
    representative: true,
    style: s({
      fontFamily: "Playfair Display",
      fontWeight: 600,
      fontSize: 56,
      textCase: "sentence",
      letterSpacing: 1,
      color: "#FAF7F2",
      outlineEnabled: false,
      shadowEnabled: true,
      shadowBlur: 14,
      x: 8,
      y: 86,
      align: "left",
      boxWidthPercent: 66,
      wordHighlight: false,
    }),
    animation: a({ entrance: "fade", exit: "fade", word: "none", durationSec: 0.5 }),
  },
  {
    id: "magazine",
    name: "Magazine",
    description: "Small wide-tracked serif caps pinned top-right, like a pull-quote byline.",
    family: "editorial",
    representative: true,
    style: s({
      fontFamily: "Playfair Display",
      fontWeight: 800,
      fontSize: 46,
      textCase: "uppercase",
      letterSpacing: 4,
      color: "#F5F0E6",
      outlineEnabled: false,
      shadowBlur: 8,
      shadowOpacity: 0.7,
      x: 94,
      y: 10,
      align: "right",
      vAlign: "top",
      boxWidthPercent: 56,
      wordHighlight: false,
    }),
    animation: a({ entrance: "slide-left", exit: "fade", word: "none", durationSec: 0.5 }),
  },
  {
    id: "elegant",
    name: "Elegant",
    description: "Light weight, generous spacing, sentence case.",
    family: "editorial",
    style: s({ fontFamily: "DM Sans", fontWeight: 500, fontSize: 48, letterSpacing: 2.5, textCase: "sentence", outlineWidth: 3, y: 84, wordHighlight: false }),
    animation: a({ entrance: "slide-up", exit: "fade", word: "none", durationSec: 0.5 }),
  },
  {
    id: "luxury",
    name: "Luxury",
    description: "Small champagne-gold serif capitals with very wide tracking — refined and high-end.",
    family: "editorial",
    style: s({
      fontFamily: "Playfair Display",
      fontWeight: 700,
      fontSize: 46,
      textCase: "uppercase",
      letterSpacing: 6,
      color: "#F5E1A4",
      outlineEnabled: false,
      shadowEnabled: true,
      shadowBlur: 12,
      y: 80,
      wordHighlight: false,
    }),
    animation: a({ entrance: "fade", exit: "fade", word: "none", durationSec: 0.5 }),
  },

  // ───────────────────────── Cinematic ─────────────────────────
  {
    id: "cinematic",
    name: "Cinematic",
    description: "Warm white, letter-spaced, a soft film-subtitle shadow near the bottom.",
    family: "cinematic",
    representative: true,
    style: s({
      fontFamily: "DM Serif Display",
      fontWeight: 400,
      fontSize: 50,
      textCase: "sentence",
      letterSpacing: 2,
      y: 88,
      outlineEnabled: false,
      shadowEnabled: true,
      shadowBlur: 18,
      shadowOffsetY: 3,
      color: "#F5F5F0",
      wordHighlight: false,
    }),
    animation: a({ entrance: "fade", exit: "fade", word: "none", durationSec: 0.4 }),
  },
  {
    id: "film-title",
    name: "Film Title",
    description: "Tiny, ultra-wide-tracked capitals at the very bottom, rising slowly like end-credit subtitles.",
    family: "cinematic",
    representative: true,
    style: s({
      fontFamily: "Montserrat",
      fontWeight: 500,
      fontSize: 42,
      textCase: "uppercase",
      letterSpacing: 8,
      color: "#E8E6E0",
      outlineEnabled: false,
      shadowEnabled: true,
      shadowBlur: 22,
      shadowOpacity: 0.7,
      y: 93,
      wordHighlight: false,
    }),
    animation: a({ entrance: "slide-up", exit: "fade", word: "none", durationSec: 0.6 }),
  },
  {
    id: "cinematic-glow",
    name: "Cinematic Glow",
    description: "A cool blue glow behind elegant serif text, brightening on the active word.",
    family: "cinematic",
    style: s({
      fontFamily: "DM Serif Display",
      fontWeight: 400,
      fontSize: 54,
      textCase: "sentence",
      outlineEnabled: false,
      shadowEnabled: true,
      shadowColor: "#60A5FA",
      shadowBlur: 20,
      shadowOpacity: 0.8,
      wordHighlight: true,
      highlightColor: "#93C5FD",
    }),
    animation: a({ entrance: "fade", word: "color", durationSec: 0.4 }),
  },
  {
    id: "soft-shadow",
    name: "Soft Shadow",
    description: "Big, bold sentence-case text lifted off busy footage by a deep, soft shadow.",
    family: "cinematic",
    style: s({
      fontFamily: "Montserrat",
      fontWeight: 700,
      fontSize: 60,
      textCase: "sentence",
      letterSpacing: 1,
      outlineEnabled: false,
      shadowEnabled: true,
      shadowBlur: 28,
      shadowOffsetY: 4,
      shadowOpacity: 0.85,
      y: 84,
      wordHighlight: false,
    }),
    animation: a({ entrance: "slide-up", exit: "fade", word: "none", durationSec: 0.4 }),
  },

  // ───────────────────────── Neon ─────────────────────────
  {
    id: "neon",
    name: "Neon",
    description: "Glowing neon-green capitals that pop in, with a hot-pink glow on the active word.",
    family: "neon",
    representative: true,
    style: s({
      fontFamily: "Archivo",
      fontWeight: 800,
      fontSize: 62,
      textCase: "uppercase",
      color: "#39FF88",
      outlineEnabled: false,
      shadowEnabled: true,
      shadowColor: "#39FF88",
      shadowBlur: 26,
      shadowOpacity: 0.9,
      wordHighlight: true,
      highlightColor: "#FF3EC9",
    }),
    animation: a({ entrance: "pop", exit: "fade", word: "color", durationSec: 0.25 }),
  },
  {
    id: "neon-tube",
    name: "Neon Tube",
    description: "Tall white tube lettering ringed in cyan with a magenta halo, bouncing in.",
    family: "neon",
    representative: true,
    style: s({
      fontFamily: "Bebas Neue",
      fontWeight: 400,
      fontSize: 84,
      textCase: "uppercase",
      letterSpacing: 4,
      color: "#FFFFFF",
      outlineEnabled: true,
      outlineColor: "#22D3EE",
      outlineWidth: 4,
      shadowEnabled: true,
      shadowColor: "#FF3EC9",
      shadowBlur: 30,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      shadowOpacity: 1,
      y: 70,
      wordHighlight: true,
      highlightColor: "#FF3EC9",
    }),
    animation: a({ entrance: "bounce", exit: "fade", word: "color", durationSec: 0.3 }),
  },
  {
    id: "gradient-glow",
    name: "Gradient Glow",
    description: "Pink text against a contrasting blue glow — a two-tone gradient feel.",
    family: "neon",
    style: s({
      fontFamily: "Outfit",
      fontWeight: 700,
      fontSize: 60,
      textCase: "none",
      color: "#F472B6",
      outlineEnabled: false,
      shadowEnabled: true,
      shadowColor: "#38BDF8",
      shadowBlur: 22,
      shadowOpacity: 0.85,
      wordHighlight: true,
      highlightColor: "#FDE047",
    }),
    animation: a({ entrance: "fade", word: "color" }),
  },
  {
    id: "outline",
    name: "Outline",
    description: "A big, vivid cyan outline does all the work — bold graphic emphasis.",
    family: "neon",
    style: s({ fontFamily: "Archivo", fontWeight: 900, fontSize: 68, textCase: "uppercase", outlineColor: "#22D3EE", outlineWidth: 9, wordHighlight: false }),
    animation: a({ entrance: "fade", word: "none" }),
  },
  {
    id: "vhs",
    name: "VHS",
    description: "Cyan capitals with a hard magenta fringe — a worn videotape look.",
    family: "neon",
    // Was cyan text inside a thick PINK outline, which merged into one pink smear and lost the cyan.
    // The fringe is now a hard offset magenta shadow behind clean, unoutlined cyan letters.
    style: s({
      fontFamily: "Oswald",
      fontWeight: 600,
      fontSize: 76,
      textCase: "uppercase",
      color: "#67E8F9",
      outlineEnabled: false,
      shadowEnabled: true,
      shadowColor: "#F472B6",
      shadowBlur: 0,
      shadowOffsetX: 6,
      shadowOffsetY: 6,
      shadowOpacity: 1,
      wordHighlight: true,
      highlightColor: "#FDE047",
    }),
    animation: a({ entrance: "fade", word: "color" }),
  },
  {
    id: "arcade",
    name: "Arcade",
    description: "Blocky condensed caps, purple glow, hot-pink active word — 8-bit energy.",
    family: "neon",
    style: s({
      fontFamily: "League Spartan",
      fontWeight: 800,
      fontSize: 60,
      textCase: "uppercase",
      color: "#39FF14",
      outlineColor: "#7C3AED",
      outlineWidth: 6,
      shadowEnabled: true,
      shadowColor: "#7C3AED",
      shadowBlur: 14,
      shadowOpacity: 0.7,
      wordHighlight: true,
      highlightColor: "#FF3EC9",
      activeWordScale: 1.2,
    }),
    animation: a({ entrance: "pop", word: "scale", durationSec: 0.15 }),
  },

  // ───────────────────────── Sticker ─────────────────────────
  {
    id: "sticker",
    name: "Sticker",
    description: "Dark text on a bright, rounded sticker chip — peel-and-stick energy.",
    family: "sticker",
    representative: true,
    style: s({
      fontFamily: "Fredoka",
      fontWeight: 700,
      fontSize: 60,
      textCase: "none",
      color: "#1E293B",
      backgroundColor: "#FDE047",
      backgroundOpacity: 1,
      backgroundRadius: 24,
      backgroundPaddingX: 22,
      backgroundPaddingY: 12,
      outlineEnabled: false,
      wordHighlight: false,
    }),
    animation: a({ entrance: "pop", word: "none", durationSec: 0.2 }),
  },
  {
    id: "sticker-pill",
    name: "Sticker Pill",
    description: "White lowercase text on a hot-pink pill, sitting higher up and bouncing in, with a yellow word accent.",
    family: "sticker",
    representative: true,
    style: s({
      fontFamily: "Baloo 2",
      fontWeight: 800,
      fontSize: 64,
      textCase: "lowercase",
      color: "#FFFFFF",
      backgroundColor: "#EC4899",
      backgroundOpacity: 1,
      backgroundRadius: 60,
      backgroundPaddingX: 34,
      backgroundPaddingY: 14,
      outlineEnabled: false,
      shadowEnabled: false,
      y: 68,
      wordHighlight: true,
      highlightColor: "#FDE047",
    }),
    // Colour-only word accent: ASS draws a caption box per line at the height of its tallest run, so a
    // scaled word would make the pill bulge around it in the export.
    animation: a({ entrance: "bounce", exit: "pop", word: "color", durationSec: 0.3 }),
  },
  {
    id: "reels",
    name: "Reels",
    description: "Rounded background chips, Instagram-native feel.",
    family: "sticker",
    style: s({
      fontFamily: "Plus Jakarta Sans",
      fontWeight: 700,
      fontSize: 56,
      backgroundColor: "#000000",
      backgroundOpacity: 0.55,
      backgroundRadius: 20,
      outlineEnabled: false,
      wordHighlight: true,
      highlightColor: "#F472B6",
    }),
    animation: a({ entrance: "slide-up", word: "highlight" }),
  },
  {
    id: "retro",
    name: "Retro",
    description: "Warm cream text on a burnt-orange chip — 70s poster energy.",
    family: "sticker",
    style: s({
      fontFamily: "Oswald",
      fontWeight: 500,
      fontSize: 58,
      textCase: "uppercase",
      color: "#F5E6D3",
      backgroundColor: "#C2410C",
      backgroundOpacity: 0.85,
      backgroundRadius: 4,
      backgroundPaddingX: 16,
      backgroundPaddingY: 8,
      outlineEnabled: false,
      wordHighlight: false,
    }),
    animation: a({ entrance: "fade", word: "none" }),
  },
  {
    id: "candy-pop",
    name: "Candy Pop",
    description: "Bubblegum pink with a baby-blue pop on every active word.",
    family: "sticker",
    style: s({
      fontFamily: "Quicksand",
      fontWeight: 700,
      fontSize: 62,
      textCase: "none",
      color: "#FF6FB5",
      outlineColor: "#FFFFFF",
      outlineWidth: 6,
      wordHighlight: true,
      highlightColor: "#7DD3FC",
      activeWordScale: 1.2,
    }),
    animation: a({ entrance: "bounce", word: "scale", durationSec: 0.25 }),
  },

  // ───────────────────────── Comic ─────────────────────────
  {
    id: "comic",
    name: "Comic",
    description: "Bangers comic lettering high in the frame, a fat black outline, popping in with a yellow word hit.",
    family: "comic",
    representative: true,
    style: s({
      fontFamily: "Bangers",
      fontWeight: 400,
      fontSize: 100,
      textCase: "uppercase",
      letterSpacing: 2,
      outlineColor: "#111827",
      outlineWidth: 10,
      y: 24,
      vAlign: "center",
      wordHighlight: true,
      highlightColor: "#FDE047",
      activeWordScale: 1.2,
    }),
    animation: a({ entrance: "pop", word: "scale", durationSec: 0.15 }),
  },
  {
    id: "cartoon",
    name: "Cartoon",
    description: "Playful green with a bold dark outline and a bouncy active word.",
    family: "comic",
    representative: true,
    style: s({
      fontFamily: "Baloo 2",
      fontWeight: 600,
      fontSize: 76,
      textCase: "none",
      color: "#34D399",
      outlineColor: "#111827",
      outlineWidth: 7,
      wordHighlight: true,
      highlightColor: "#FBBF24",
      activeWordScale: 1.2,
    }),
    animation: a({ entrance: "bounce", word: "bounce", durationSec: 0.25 }),
  },
  {
    id: "bounce",
    name: "Bounce",
    description: "The whole caption springs onto screen, then a gentle color change per word.",
    family: "comic",
    style: s({ fontFamily: "Fredoka", fontWeight: 600, fontSize: 62, outlineWidth: 5, wordHighlight: true, highlightColor: "#38BDF8" }),
    animation: a({ entrance: "bounce", word: "highlight", durationSec: 0.3 }),
  },
  {
    id: "shadow-pop",
    name: "Shadow Pop",
    description: "A hard, offset pop-art drop shadow with no blur at all.",
    family: "comic",
    style: s({
      fontFamily: "Archivo Black",
      fontWeight: 400,
      fontSize: 66,
      textCase: "uppercase",
      outlineEnabled: false,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowOffsetX: 6,
      shadowOffsetY: 6,
      shadowBlur: 0,
      shadowOpacity: 1,
      wordHighlight: true,
      highlightColor: "#FACC15",
      activeWordScale: 1.15,
    }),
    animation: a({ entrance: "pop", word: "scale", durationSec: 0.15 }),
  },

  // ───────────────────────── Podcast ─────────────────────────
  {
    id: "podcast",
    name: "Podcast",
    description: "Readable sentence-case text on a soft dark panel, left-aligned in the lower third.",
    family: "podcast",
    representative: true,
    style: s({
      fontFamily: "Nunito",
      fontWeight: 700,
      fontSize: 48,
      textCase: "sentence",
      outlineEnabled: false,
      shadowEnabled: false,
      backgroundColor: "#0B1220",
      backgroundOpacity: 0.55,
      backgroundRadius: 14,
      x: 6,
      y: 90,
      align: "left",
      boxWidthPercent: 72,
      wordHighlight: true,
      highlightColor: "#A78BFA",
    }),
    animation: a({ entrance: "slide-up", exit: "fade", word: "color", durationSec: 0.3 }),
  },
  {
    id: "youtube",
    name: "YouTube",
    description: "Wide, readable, landscape-friendly captions.",
    family: "podcast",
    representative: true,
    style: s({
      fontFamily: "Roboto",
      fontWeight: 600,
      fontSize: 44,
      y: 90,
      boxWidthPercent: 70,
      backgroundColor: "#000000",
      backgroundOpacity: 0.6,
      outlineEnabled: false,
      wordHighlight: false,
    }),
    animation: a({ entrance: "fade", word: "none" }),
  },

  // ───────────────────────── Documentary ─────────────────────────
  {
    id: "news",
    name: "News",
    description: "Broadcast-style lower third bar.",
    family: "documentary",
    representative: true,
    style: s({
      fontFamily: "Oswald",
      fontWeight: 500,
      fontSize: 56,
      textCase: "uppercase",
      y: 92,
      boxWidthPercent: 90,
      backgroundColor: "#B91C1C",
      backgroundOpacity: 1,
      backgroundRadius: 0,
      outlineEnabled: false,
      color: "#FFFFFF",
      wordHighlight: false,
    }),
    animation: a({ entrance: "slide-left", word: "none" }),
  },
  {
    id: "documentary",
    name: "Documentary",
    description: "Small tracked caps on a deep-navy square bar, flush-left at the bottom with an amber word accent.",
    family: "documentary",
    representative: true,
    style: s({
      fontFamily: "Manrope",
      fontWeight: 700,
      fontSize: 40,
      textCase: "uppercase",
      letterSpacing: 3,
      color: "#F8FAFC",
      outlineEnabled: false,
      shadowEnabled: false,
      backgroundColor: "#0F172A",
      backgroundOpacity: 0.85,
      backgroundRadius: 2,
      backgroundPaddingX: 24,
      backgroundPaddingY: 12,
      x: 5,
      y: 95,
      align: "left",
      boxWidthPercent: 56,
      wordHighlight: true,
      highlightColor: "#FBBF24",
    }),
    animation: a({ entrance: "fade", exit: "fade", word: "color", durationSec: 0.4 }),
  },

  // ───────────────────────── Meme ─────────────────────────
  {
    id: "meme-impact",
    name: "Meme Impact",
    description: "Enormous white Anton capitals with a fat black outline across the top of the frame.",
    family: "meme",
    representative: true,
    style: s({
      fontFamily: "Anton",
      fontWeight: 400,
      fontSize: 100,
      textCase: "uppercase",
      outlineColor: "#000000",
      outlineWidth: 14,
      shadowEnabled: false,
      y: 5,
      vAlign: "top",
      boxWidthPercent: 92,
      wordHighlight: false,
    }),
    animation: a({ entrance: "pop", exit: "none", word: "none", durationSec: 0.12 }),
  },
  {
    id: "meme-yellow",
    name: "Meme Yellow",
    description: "Giant yellow Archivo Black capitals jammed against the bottom edge, no animation at all.",
    family: "meme",
    representative: true,
    style: s({
      fontFamily: "Archivo Black",
      fontWeight: 400,
      fontSize: 90,
      textCase: "uppercase",
      color: "#FFE600",
      outlineColor: "#000000",
      outlineWidth: 12,
      y: 96,
      boxWidthPercent: 94,
      wordHighlight: false,
    }),
    animation: a({ entrance: "none", exit: "none", word: "none", durationSec: 0.1 }),
  },
  {
    id: "word-burst",
    name: "Word Burst",
    description: "A dramatic, oversized scale burst on every emphasized word, mid-screen.",
    family: "meme",
    style: s({
      fontFamily: "Anton",
      fontWeight: 400,
      fontSize: 88,
      textCase: "uppercase",
      outlineWidth: 10,
      y: 38,
      vAlign: "center",
      wordHighlight: true,
      highlightColor: "#FF2D55",
      activeWordScale: 1.45,
    }),
    animation: a({ entrance: "word-pop", word: "scale", durationSec: 0.12 }),
  },

  // ───────────────────────── Handwritten ─────────────────────────
  {
    id: "handwritten-caveat",
    name: "Pen Script",
    description: "Loose Caveat pen lettering, slightly off-centre, with a yellow underline that follows the spoken word.",
    family: "handwritten",
    representative: true,
    style: s({
      fontFamily: "Caveat",
      fontWeight: 700,
      fontSize: 86,
      textCase: "none",
      color: "#FFFFFF",
      outlineColor: "#1F2937",
      outlineWidth: 4,
      shadowBlur: 8,
      x: 44,
      y: 78,
      boxWidthPercent: 70,
      wordHighlight: true,
      highlightColor: "#FDE047",
    }),
    animation: a({ entrance: "typewriter", exit: "fade", word: "underline", durationSec: 0.4 }),
  },
  {
    id: "handwritten-marker",
    name: "Marker Notes",
    description: "Kalam marker notes in the top-left, sliding in like a scribbled margin note, with a bouncing pink word.",
    family: "handwritten",
    representative: true,
    style: s({
      fontFamily: "Kalam",
      fontWeight: 700,
      fontSize: 60,
      textCase: "sentence",
      color: "#FDE68A",
      outlineColor: "#000000",
      outlineWidth: 5,
      x: 8,
      y: 18,
      align: "left",
      vAlign: "top",
      boxWidthPercent: 70,
      wordHighlight: true,
      highlightColor: "#FB7185",
      activeWordScale: 1.15,
    }),
    animation: a({ entrance: "slide-right", exit: "fade", word: "bounce", durationSec: 0.4 }),
  },

  // ───────────────────── Folded into another preset (hidden, resolvable) ─────────────────────
  {
    id: "clean",
    name: "Clean",
    description: "Soft shadow only, no outline, editorial feel.",
    family: "minimal",
    replacedBy: "classic",
    style: s({ fontFamily: "Inter", fontWeight: 600, fontSize: 52, outlineEnabled: false, shadowEnabled: true, shadowBlur: 16, wordHighlight: false }),
    animation: a({ entrance: "fade", word: "none" }),
  },
  {
    id: "clean-white",
    name: "Clean White",
    description: "Pure white text, a whisper of shadow, nothing else competing for attention.",
    family: "minimal",
    replacedBy: "classic",
    style: s({ fontFamily: "Inter", fontWeight: 500, fontSize: 50, textCase: "sentence", outlineWidth: 2, shadowEnabled: true, shadowBlur: 8, shadowOpacity: 0.35, wordHighlight: false }),
    animation: a({ entrance: "fade", word: "none" }),
  },
  {
    // Task 146220 (P19.17): `id` and `entrance: "typewriter"` kept as-is (existing projects/saved
    // styles reference this id) — see lib/subtitles/animation-render.ts: this entrance is the same
    // capped ~150ms fade as every other approximated entrance, not a progressive reveal.
    id: "typewriter",
    name: "Wide Type",
    description: "Even, wide letter spacing with a quick fade-in.",
    family: "minimal",
    replacedBy: "mono",
    style: s({ fontFamily: "Roboto", fontWeight: 500, fontSize: 48, textCase: "none", letterSpacing: 2, outlineWidth: 2, wordHighlight: false }),
    animation: a({ entrance: "typewriter", word: "none", durationSec: 0.4 }),
  },
];

export function getPreset(id: string): SubtitlePresetDef | undefined {
  return BUILT_IN_PRESETS.find((p) => p.id === id);
}

export function presetsByFamily(family: StyleFamily): SubtitlePresetDef[] {
  return BUILT_IN_PRESETS.filter((p) => p.family === family);
}

/** Presets shown in the picker: everything except presets folded into another (`replacedBy`). */
export const PICKER_PRESETS: SubtitlePresetDef[] = BUILT_IN_PRESETS.filter((p) => !p.replacedBy);

/** Picker presets of one family, its two flagship (`representative`) styles first. */
export function pickerPresetsByFamily(family: StyleFamily): SubtitlePresetDef[] {
  const inFamily = PICKER_PRESETS.filter((p) => p.family === family);
  return [...inFamily.filter((p) => p.representative), ...inFamily.filter((p) => !p.representative)];
}
